### ISSUE TITLE
Consider adding a cleaner based on scrub-a-dub

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/vcrpy-cleaner#8]
scrub-a-dub has sensitive data detectors and cleaners.
We should have a look at whether our use cases are made simpler by implementing cleaner functions we need on top of scrub-a-dub.
https://scrubadub.readthedocs.io/en/stable/

- [x] Review features the scrub a dub has
- [x] Open new issues for anything we want to add

**Comment by edthedev** [comment]
Work moved to https://github.com/techservicesillinois/secops-soar-tdx/issues/29

**Comment by zdc217** [comment]
We looked at this on the afternoon ensemble. We decided to try scrubbing some cassettes and the scrubadub install fails due to a deprecated dependency. Looking at their source, the last release was 10/2021 and although there are some recent commits, there doesn't appear much activity on the development. We stopped there.

**Comment by edthedev** [comment]
Closing this as a dead end, for now. Might revisit if we find a strong need.
